### ISSUE TITLE
Hard code readings in the monitoring survey for Naira - 20th feb 2024

### ISSUE THREAD

**Issue by Archi11Gupta** [DevInnovationLab/i-h2o-india#104]
Today, in Naira, the surveyor received a reading of 2.4 ppm (this was a 2nd test) from the MR meter at the farthest household then he switched to the HR meter and the reading was 0.25 ppm which shouldn’t be the case, and even in the form he is unable to fill it because of the constraint we have put. The first reading was around 0.94 ppm. So, to submit the form surveyor will input 8.8 in the HR reading section and reflect on the situation in the comments. So, the actual reading of 0.25 ppm for HR testing needs to be hard-coded.

**Comment by jlowe-git** [comment]
Hi Archi,
With cases like this, can you also supply the HH ID so we can reference and make the changes?

**Comment by Archi11Gupta** [comment]
Hi Jeremy,

We don't collect HHIDs in monitoring surveys. The value to be edited can be
identified by the village name and date so it is easier to delete don't
worry I am incorporating all these little things in my quality checks. Once
it's all ready I will share it with you.
Thanks and Regards,
Archi

**Comment by jlowe-git** [comment]
Ah right, sorry forgot. Thanks for working on identifying it that way.

**Comment by Archi11Gupta** [comment]
This is done
