### ISSUE TITLE
Follow up R1 - Duplicate sample IDs?

### ISSUE THREAD

**Issue by jlowe-git** [DevInnovationLab/i-h2o-india#110]
Hi @Archi11Gupta ,

@mich1995 was checking the E. coli data and came across duplicate IDs for a 6 samples in the IDEXX results. I haven't had a chance to look at the hard copy data yet, but could you work with Ishadatta to double check some of the R1 IDEXX results for why these duplicates happened?

I don't think duplicates were entered into survey data, but my hunch is that it's from lab data/happened during transcription.

[Duplicates in Ecoli data_Followup R1.xlsx](https://github.com/DevInnovationLab/i-h2o-india/files/14675677/Duplicates.in.Ecoli.data_Followup.R1.xlsx)

**Comment by niharika-bhagavatula** [comment]
Duplicates not present in the FU Round 1 data (possibly corrected in the raw data) - Marking issue as resolved
