### ISSUE TITLE
Manual corrections in Endline census - 26th apr 2024 (Explanation behind prefix 111 in the household names)

### ISSUE THREAD

**Issue by Archi11Gupta** [DevInnovationLab/i-h2o-india#116]
During the Endline census, we came across cases where either the age or gender of respondent/hh members was incorrectly noted during baseline census (In case of UID "50101-119-006", HH Member "Rukmani Nagabansa" was listed as Male in Baseline but is actually a Female).  Enumerators were instructed to list such members' names again under the new member roster with correct information.  The enumerators added the prefix 111 to the names of such respondents in the new roster for easy identification. Need to identify these cases and reconcile changes to roster information. |

NOTE: This re-entry was supposed to be done only for the cases where including the member in the new roster will help them become eligible for other sections. For eg- if the person was of age 43 and male in the baseline census and in endline we found that this is woman of age 43 we would include her in the new roster so that she is eligible for the women section. Only for such cases where re-entering them would make them eligible for women or child section we would include them in the roster.

**Comment by Archi11Gupta** [comment]
Niharika to close this off if the change is done in the baseline HH dataset

**Comment by niharika-bhagavatula** [comment]
Found 15 such cases where the members' details were incorrectly mentioned in baseline and were added to new member roster (also includes cases where members are non-CBW women) : Made manual correction to the relevant baseline age and gender variables + Endline variable : count of new members accordingly
In case of UID 50101119006: Gender of the respondent "Rukmani Katabansa" changed to Female (her details not mentioned in new roster by the enumerator again so we will just correct her gender in the baseline census)
