### ISSUE TITLE
Endline census data- drop data before 21st Apr 2024

### ISSUE THREAD

**Issue by Archi11Gupta** [DevInnovationLab/i-h2o-india#119]
I see some practice entries in the endline consented dataset. In the final dataset, we must drop entries before 21st Apr 2024 and there was one entry where the key is R_E_key == "uuid:54261fb3-0798-4528-9e85-3af458fdbad9". This was a practice entry that I sent after 21st Apr 2024 to check for audio recordings.  I have dropped it in my BC preload do file. This also must be dropped in endline HFCs

**Comment by niharika-bhagavatula** [comment]
No observations submitted before Apr 21 present in the Master HH Level dataset

**Comment by Archi11Gupta** [comment]
Have we dropped this key  "uuid:54261fb3-0798-4528-9e85-3af458fdbad9"?

**Comment by niharika-bhagavatula** [comment]
the observation with key R_E_key == "uuid:54261fb3-0798-4528-9e85-3af458fdbad9" is not present in the Master HH level dataset. Marking issue as resolved
