### ISSUE TITLE
Endline census dataset- calculation of variables from new member roster

### ISSUE THREAD

**Issue by Archi11Gupta** [DevInnovationLab/i-h2o-india#121]
We should create calculated variables in stata from gender and age present because after the survey launched there were some constraints and changes that had to be made due to which there can be slight differences in the variables that are calculated in survey cto so to be super sure we must create these variables on our own too. Especially variable N_num_childbelow5 might have some slight difference but I corrected it afterwards but still to have correct stats e should create variables on our own too to cross check. 

N_female_above12
N_num_femaleabove12
N_male_above12
N_num_maleabove12
N_adults_hh_above12
N_num_adultsabove12
N_children_below12
N_num_childbelow12
N_female_15to49
N_num_female_15to49
N_children_below5
N_num_childbelow5
N_allmembers_H
N_num_allmembers_H

**Comment by Archi11Gupta** [comment]
This process has to be administered in the individual roster dataset for endline census

**Comment by niharika-bhagavatula** [comment]
Created following new variables in Master HH level dataset:

R_Cen_hhmember_count "Number of HH members in Baseline"
C_E_n_hhmember_count "Number of New HH members in Endline"
C_total_hhmembers "Total number of HH members: Baseline and Endline"
C_total_U5children "Total number of U5 children: Baseline and Endline"
C_E_total_pregnant "Total number of Pregnant women in Endline"
C_total_CBW "Total number women of child bearing age: Baseline and Endline"
C_total_noncri_members "Total number non-criteria members: Baseline and Endline"
C_total_female_above12 "Total number of females above 12 years: Baseline and Endline"
C_total_male_above12 "Total number of males above 12 years: Baseline and Endline"
C_total_members_above12 "Total HH members above 12 years: Baseline and Endline"
C_total_members_below12 "Total HH members below 12 years: Baseline and Endline"

Similar variables for Baseline and Endline have also been created (similar variable names and labels have been used for consistency and easy identification. Prefix for baseline variables: C_Cen_; Prefix for endline variables: C_E_n_)
