### ISSUE TITLE
Endline Census Data -- Secondary Source Use

### ISSUE THREAD

**Issue by jlowe-git** [DevInnovationLab/i-h2o-india#131]
Hi @Archi11Gupta, wanted to flag something to you in the WASH HFC for the endline census. 

There are 167 households so far who say they use a secondary water source. Out of these, 46 has given an "other" reason as to why they use a secondary source. Most of these "other" cases are electricity issues. We were intending for people to use the option for "Primary source is not working" if there were electricity issues.

At this point, I think they should just continue reporting electricity issues at "other," and then we we do data cleaning we'll combine this with the "Primary water source is not working" selections. So I think the only action to take right now is to clarify with the team that these electricity issue cases should continue to be reported in "other". Thanks!

**Comment by niharika-bhagavatula** [comment]
Categorised the other category responses into the applicable category - "Primary source not working" in the Master HH level dataset --> Marking issue as closed
