### ISSUE TITLE
Endline census - Reasons for changing main respondent (The one that answers WASH section)

### ISSUE THREAD

**Issue by Archi11Gupta** [DevInnovationLab/i-h2o-india#136]
30501-107-008 - Anita Mandingi cannot hear properly and there was no one in the house who could help in conveying the questions to her 

Village-Bhujbal
Id-30501-107-052 - Gudia pardi was noted down as the main respondent in baseline but there is no one with this name in the HH so the survey was done with Rohini Pardi and Gudia Pardi was also not in the roster 

30501-117-025
Target Respondent from baseline was S.Mansha who only knows Telugu and there was no translator present at the HH that is why WASH section and health expenditure section for non criteria members was done with  S Dhanalaxmi. S. Mansha has 2 U5 kids too so that section wasn't administered to her along with child bearing women section and surveyor marked 3rd option to move forward I..e respondent is unavailable because this option wasn't available earlier so he had to mark something but survey isn't possible here 

50301-117-008
Survey wasn't administered to Sanju sahu because she couldn't speak and has some medical issues

**Comment by Archi11Gupta** [comment]
We must check in the household level data if the enums have reflected these reasons or the respondent name has really been changed.

**Comment by niharika-bhagavatula** [comment]
Enumerators flagged in the end_comments variable that certain sections of survey were not administered to specific members of the HHs mentioned above. Also created a variable "survey_issues" in HH level dataset to reflect the same. - Marking as closed
