### ISSUE TITLE
Endline census- HHID doesn't exist

### ISSUE THREAD

**Issue by Archi11Gupta** [DevInnovationLab/i-h2o-india#138]
30501-119-006- In the village of Bhujbala this ID doesn't exist. Please investigate this more

**Comment by Archi11Gupta** [comment]
We found 2 IDs which were not found in the villages mentioned respectively. Upon further investigation, we found that the villages for these 2 IDs were interchanged. These cases have been highlighted in blue in the sheet - ID_confirmation in the google sheet- https://docs.google.com/spreadsheets/d/19XPg89gBBuGQfgPj8kngfFWoK952YZgjCK1q8qZjSeU/edit?gid=963137747#gid=963137747 

Manually correct the village names across baseline and endline

**Comment by Archi11Gupta** [comment]
After we get a final confirmation, This replacement must be done in all the datasets. for the village name

**Comment by niharika-bhagavatula** [comment]
The village IDs for the two observations were incorrectly mentioned in the survey (case of data entry error). Manually corrected the same across all datasets. - Marking issue as resolved
