### ISSUE TITLE
Gopi kankubadi's device not opened - 20th May 2024

### ISSUE THREAD

**Issue by Archi11Gupta** [DevInnovationLab/i-h2o-india#142]
Gopikankubadi Device Operation Inquiry

The pump operator informed our surveyor that he was instructed to keep the device closed when the pump is off. He stated that he only opens the device when he turns on the pump, which means it is only active when filling the tank. Today, when our surveyor requested the device to be opened, the operator said it is only opened when the pump is first turned on in the morning, resulting in water still coming from the taps when testing happened

**Comment by jlowe-git** [comment]
Settled on WhatsApp -- This was a case where the pump operator had closed the device since they were not running their pump. This village has a backflow issue so they must open/close valves each time they pump water. No action needs to be taken.
