### ISSUE TITLE
Follow-up Round 1 -- IDEXX data transcription errors

### ISSUE THREAD

**Issue by jlowe-git** [DevInnovationLab/i-h2o-india#162]
Several IDs in the R1 IDEXX data were not transcribed correctly. These IDs were:

10092
20073 
20075
20076
20087 
20089 

All were duplicated because the IDs were incorrectly entered, or the lab tech marked them twice on a single datasheet to clarify a counting error. I have corrected these in the raw data transcription file before cleaning.

**Comment by niharika-bhagavatula** [comment]
Marking this issue closed, given that changes have been made to the transcription file
