### ISSUE TITLE
0_Master_HH_Level.dta - Respondent not a member of the HH

### ISSUE THREAD

**Issue by niharika-bhagavatula** [DevInnovationLab/i-h2o-india#164]
Unique ID: 30501107052
The household has three members and the main respondent,"Gudia Pardi" is not a member of this household. She was the respondent for a household where her brother, sister in law and nephew are the members. 
Dropping this observation temporarily in the do file: "Descriptives_HHCharacteristics.do" for the generation of descriptive stats 
One alternative is to replace the respondent information for this HH with the information of Gudia Pardi, who is also a respondent and member of another HH with unique id: 30501107054 (she would still not be counted as part of this HH)

**Comment by AkitoKamei** [comment]
Re: One alternative is to replace the respondent information for this HH with the information of Gudia Pardi, who is also a respondent and member of another HH with unique id: 30501107054 (she would still not be counted as part of this HH)

But the info of "30501107054" is already in sample with another main respondents?

My suggestion is to simply replace the info into missing or drop this observation if her info does not reflect the info of the HH

**Comment by niharika-bhagavatula** [comment]
Yes, "Gudia Pardi" was the main respondent of the household for unique id "30501107054" as well. She is part of that household.
I have dropped this observation for the table creation; we will make sure to do the same for other tables moving forward as well!

**Comment by niharika-bhagavatula** [comment]
Dropped the observation from Master HH level dataset --> Marking as closed
