### ISSUE TITLE
20231002 - Baseline Survey Updates - WQ Testing Module

### ISSUE THREAD

**Issue by jlowe-git** [DevInnovationLab/i-h2o-india#39]
Hi @avohra29, detailing some of the changes to the WQ module here. None of these will dramatically change the module as it is, but they will help us address any future issues with IDs, etc.

1. See tracked changes for a couple new changes in this document: https://docs.google.com/document/d/1tbww2sNPQA4CpEstAQgz_ApL2qew3gkjWNNyCduw6mY/edit
Primary changes are updating to include a second ID check for the sample ID for both samples (including the constraints in the survey), and including further instructions for the enumerators.

2. Update constraints on the IDs to require them to be > 10000, so that no IDs can have typos that are like "1001". Also update constraints so the bag ID is greater than 90000.
3. We do not need to change variable names since we have started data collection, but somewhere in the data cleaning, can we change the variable names to be more intuitive so the final data has new names? Can also add this in later. Primarily changing:

tap_bag_ID_stored_typed -> sample_ID_stored
tap_bag_ID_running_typed -> sample_ID_tap
tap_bag_running_ID -> bag_ID_tap
tap_bag_stored_ID -> bag_ID_stored
wq_tap_fc -> fc_tap
wq_chlorine_storedfc -> fc_stored
wq_tap_tc -> tc_tap
wq_chlorine_storedtc -> tc_stored

**Comment by avohra29** [comment]
3. is done in the cleaning code now!

**Comment by avohra29** [comment]
4. Adding another question for chlorine testing to be reattempted if reading is more than or equal to 0.1

**Comment by avohra29** [comment]
@jlowe-git just confirming that bag ID should be > 900000, as its 6-digit?

**Comment by avohra29** [comment]
Implemented these changes
