### ISSUE TITLE
20231003 -- Baseline Survey WQ Testing -- Bag ID

### ISSUE THREAD

**Issue by jlowe-git** [DevInnovationLab/i-h2o-india#41]
Hi @avohra29, we have an issue in the follow-up survey where the bag IDs require a number that is 6 digits long (900000), but it is supposed to be 5 digits long (90000). So the field team isn't able to input the bag IDs into the survey today. I'll follow up on this thread later with which sample IDs match which bag IDs so we can correct the survey data. For now, the team is inputting 999999 so they can proceed through the survey.
Thanks!

**Comment by jlowe-git** [comment]
I just realized in my survey updates on the doc yesterday I said 6 digit ID, but it was incorrect and it's supposed to be 5. Made a typo -- sorry for the confusion.

**Comment by avohra29** [comment]
@jlowe-git I have corrected this in SurveyCTO, Archi told me about this. So it is working in the new form version. I will correct this in the cleaning code for the 99999 cases.
