### ISSUE TITLE
Data Issue - Baseline HH Survey from Day 1, 1st October 2023 

### ISSUE THREAD

**Issue by avohra29** [DevInnovationLab/i-h2o-india#51]
1. Two duplicates found: 
- **Duplicate for HHID: 40201111013**. On investigating the duplicates, found that Unique ID 40201111013 was the Orginal HH , which wasn't found, so replaced with  HHID 40201111012. However the entry for these IDs have not been entered correctly, i.e. In the entry for Unique ID, it should be 40201111012 (instead of 40201111013) and the entry for replacement ID, is should be 40201111013 (instead of 40201111012)
      **Action:** Replaced the correct HHID with the incorrect one
 
- **Duplicate for 50301106017** : This is an incomplete entry, so keeping the complete entry, and dropped the duplicate. 
     **Action:**  Dropping this duplicate
2. **Not found an entry** for HHID 40201110007 which was replaced, asked the enumerator/ supervisor to confirm why this household wasnt found. 
    **Action:**  Astha/ @Archi11Gupta  will submit this missing form for our records.

**Comment by Archi11Gupta** [comment]
The family was temporarily unavailable. Submitted the household form with the HHID - 40201110007

**Comment by niharika-bhagavatula** [comment]
No duplicates exist in Baseline HH survey or other FU rounds.
