### ISSUE TITLE
Data quality checks issues meetings with surveyors - Baseline census + baseline household, date: 9th oct 2023 (Documentation)

### ISSUE THREAD

**Issue by Archi11Gupta** [DevInnovationLab/i-h2o-india#53]
For @avohra29, 
1) chlorine testing timings for Swagatika are very low because she usually does chlorine testing before starting the section in the survey. She records results in a notebook for readings and quickly opens the section to fill in the readings. It is more convenient for her because the water supply for running water is very variable and they have to do it according to the pump operator so she writes down the readings first and then mentions it in the tablet.
2) Surveyors were also confused about submitting the form for the original household ID if not found so I demonstrated everything by sharing my screen on how they have to submit the 2 forms. Also clarified to them where to mention household ID and where to mention replacement ID.
3) Consent time for Kuna Charan was low because he reported an issue of respondents not understanding anything that was mentioned on the tablet. He would give a pre-consent without opening the consent section that's why it is very low
Action taken- 
a) Increased monitoring/ shadow checks on him by Sanjay ji and Binod ji. Sanjay Ji also reported progress in that he started reading consent from the tablet now in one of his shadow checks 
b) Since this was an issue highlighted by all the surveyors in the meeting respondents get annoyed if we read the lengthy consent in the household survey again because they say that they have already heard it in the census. To tackle the respondents' lack of understanding I told them 2 things- 
##If the respondent is similar i.e. the same respondent gave the census information then highlight only the different things about the household survey from the tablet i.e. time, gift, water quality testing, the purpose of testing water, any harms/benefits to their participation, and briefly in their language mention about the data security no need to read word to word from tablet 
##If the respondent is different i.e. the different respondent gave the census information then read the whole cost from the tablet first and then explain briefly in their words after they have read everything out 

For @mich1995 
1) Average Consent timings are still very low for all the enumerators in the stats. After enquiring with enumerators they said that most of them at least take 10 mins to read the whole consent and explain everything to them. This issue is most likely because of the inclusion of the non-consented or non-eligible forms too maybe
2) The same goes for other sections in the survey
3) Jitendra has been told about the issue he has been making, hopefully, this should improve. 
4) Yet to get an answer for the duplicate for Jaltar, will update you tomorrow 

General things from the meeting - 
1) Some respondents aren't comfortable saying the names of their in-laws because of societal rituals, in this case, if nobody else is present in the respondent's house to tell the name and neighbors aren't present to tell the name, one thing they can do is ask Asha or AWC. If they also don't know then enter na in the name section

**Comment by v-prathap** [comment]
On the last point, the entry for name should be the Don’t know error code number, and we should make sure to capture the relationship to respondent correctly.

**Comment by Archi11Gupta** [comment]
I will have to check if we can enter 999 for don't know there because it is
coded as a text field. So, that's why na was decided and yes the
relationship is captured.

Regards,
Archi

**Comment by Archi11Gupta** [comment]
@mich1995 For the duplicate in Jaltar- 20201113034 by Mangulu Bagh. 
34 HH number has been entered twice by mistake and then the surveyor entered 35 for the next one if you closely check entry of 36 is missing so you can change the numbering in a way so that 36 is reflected somewhere.
