### ISSUE TITLE
Data Issue - Oct 10th 2023, Baseline Survey, WQ Testing

### ISSUE THREAD

**Issue by jlowe-git** [DevInnovationLab/i-h2o-india#54]
Hi @avohra29 @Archi11Gupta, I caught a duplicate sample ID from sample collection in Karlakana in the HH survey. @avohra29 did your code also catch this duplicate?

Stored Sample ID 20291 was entered twice in two separate forms. I think the incorrect sample ID is the one for HH ID 50301106013. It should be 20290 instead. Can you add this to the cleaning code @avohra29?

**Comment by Archi11Gupta** [comment]
@jlowe-git can you let me know if you fund this duplicate from the tracking sheets Ishadutt shares with us? Asking so that I can also keep a track of it

**Comment by jlowe-git** [comment]
The samples were correctly entered when they reached the lab, it's just in the surveys where there was an error

**Comment by niharika-bhagavatula** [comment]
Changes made to the code file "1_2_A_Followup_cleaning.do" under Manual Corrections section
