### ISSUE TITLE
Village specific observations : JJM tap connections usage related issues (Documentation of the field update)

### ISSUE THREAD

**Issue by Archi11Gupta** [DevInnovationLab/i-h2o-india#69]
**Village 1 - Asada** 
1 hamlet at an elevation so water doesn't go easily, only when pressure is high water come 6-8 am and 8-10 households consume from their own borewell instead of JJM taps. 

 **Village 2 - Mukundpur** 
A) In one Saahi, there are 4-5 households that don't drink from JJM tap connections because they started developing health issues. But they spend a major part of their day in nearby Bherampur because of work there, so they consume water from there too they are not sure if the health issue happened because of the tap water in Mukundpur or Bherampur. 

**Village 3 - Tandipur** 
It has 2 Hamlets. One near the tank and one near the market. In the hamlet near the market, there are about 25 households out of that about 10-11 households take  water from other members' Tap connections because the amount of water they receive is much less from their own JJM tap connections

**Village 4 - Bhujbhal**
A) There are 10-12 families who don't have pipe connections because they settled there later and are present on the side of the road different from the main village area. They have tap connections from the nearby College tank, not the main JJM tank.
B) There are 8-10 households in the village which are Banjara families (Vagabonds) who live in a separate area of the village. They also have been surveyed although they don't have any JJM tap connections

**Village 5 - Sanagortha**
There is one specific hamlet, where only 4-5 households drink from JJM tap water. Others don't drink from JJM because they complained about the presence of iron pieces in the water so they drink from their handpumps. This would be more clear after the whole census is complete

**Village 6 - BK Padar**
There is one hamlet that is quite small, it has 5-6 households and they don't have JJM tap connections. This small hamlet is approximately 1.5 km away from the main village

**Comment by jlowe-git** [comment]
Thanks Archi for summarizing all of this. When we conducted our scoping, we saw this to be a common issue so we were expecting some HHs and hamlets to not have tap connections. Anyone who does not have a JJM tap connection will be dropped from the follow up surveys anyways, since it cannot be their primary water source

For Bhujbhal, do you know if they recorded the college tank at "household tap connections" in the survey?

In Sanagortha, this could be a much bigger issue missed during our scoping. @mich1995 I don't see this village listed in the Overleaf doc but I'm assuming it just needs to be updated?

**Comment by mich1995** [comment]
@jlowe-git yes I'm just updating the doc with 3 additional villages (which includes Sanagortha)

**Comment by jlowe-git** [comment]
From the updated tables it looks like Sanagortha is using JJM taps as the primary source in 86% of HHs, but this kinda goes against what you suggest @Archi11Gupta .

When you're back from the Durga Puja holiday can you confirm this with the team?

**Comment by Archi11Gupta** [comment]
Hey, Jeremy
I think I would clear this up again and this is what I mentioned- There is one specific hamlet, where only 4-5 households drink from JJM tap water. Others don't drink from JJM because they complained about the presence of iron pieces in the water so they drink from their handpumps. This would be more clear after the whole census is complete

Now I think 86% is still fine because this was an issue faced in one hamlet only where only 4-5 households were drinking from JJM tap water. Other households in the same hamlet which would be around 10-12 households don't drink from JJM tap but this issue wasn't faced in other hamlets in Sanagortha. Maybe I didn't communicate it clearly. Apologies for thr miswording 

So, it is still in line with the data.
@jlowe-git 

For Bhujbal, I will get this clarified with the supervisor and let you know
