### ISSUE TITLE
Water quality testing issue - 19th oct (Documentation)

### ISSUE THREAD

**Issue by Archi11Gupta** [DevInnovationLab/i-h2o-india#70]
In the Tandipur village in Kolnara block, HHID -30301-109-046 running water sample has been taken from a different household's tap connection because although they drink JJM tap water their tap isn't functional and works occasionally. They consume their water from that household's tap connection. 
Will give this Household's ID after confirming with the team. 

Astha and Jeremy, you can see if we are going to drop their running water test results because it hasn't been taken from their individual tap connection

**Comment by jlowe-git** [comment]
I think it is okay to keep these results. There are many of these tap connections that are less than a meter from one another, so even though it belongs to another household, they can often be really close to one another. I'm assuming they collect water and transport it from the other household which is somewhat nearby.

I think we should leave the results as is
