### ISSUE TITLE
Baseline Census - Reporting "other" water sources frequently - Oct 24, 2023

### ISSUE THREAD

**Issue by jlowe-git** [DevInnovationLab/i-h2o-india#73]
Hi @Archi11Gupta ,

I wanted to run something by you if you can also check in with the team on this. For the primary and secondary water source questions, there are many of them which are reporting "Other" as their primary/secondary water source fairly frequently (> 10% is pretty frequent, see Table 16 in the overleaf doc). Karlakana seems to be on particular concern.

Upon further look, it seems like many of these are reported as "Borewell". Can you confirm what these other "borewells" are? Manual handpumps are also borewells, but just require manual labor to pull the water up. I'm guessing these "other" borewells are relying upon something like an electric pump to pull the water up to either a hose or single tap connection, which is why the team isn't reporting them as manual handpumps. These could be considered community taps though depending on what they look like. 

@mich1995 let's wait to figure this out a bit more before we decide on how to record these responses

See table below:
![image](https://github.com/DevInnovationLab/i-h2o-india/assets/85358737/f0861dc8-2c83-4f1e-a507-475061ed9105)

**Comment by Archi11Gupta** [comment]
This I will clarify with the team tomorrow and let you know

**Comment by jlowe-git** [comment]
Making note here that these labels for borewell are for an "electric pump connected to a borewell". We have since added a survey option for follow-up round 2 to include a choice for these answers.
