### ISSUE TITLE
Issues to be checked with Field team (Discussion regarding JJM HH tap connection vs Community standpipe)

### ISSUE THREAD

**Issue by mich1995** [DevInnovationLab/i-h2o-india#74]
[](url)Hi @Archi11Gupta,

There are 2 issues that would need clarification from the field team:

1. "JJM_drink_noprimsec" in the attached excel- there are 46 cases where people report drinking JJM even if they say that JJM is not their primary or secondary water source. We would need to check these cases with the surveyors
2. "Other prim source" in the attached excel- lists out all 53 cases where people report "Other" as their primary water source. It also mentions the source they mentioned as other, which in most cases is a borewell. Jeremy would have left you a note for this on another thread on github issues.

[Data_quality.xlsx](https://github.com/DevInnovationLab/i-h2o-india/files/13141607/Data_quality.xlsx)

**Comment by Archi11Gupta** [comment]
@jlowe-git I wanted to tell you that even if it's a community standpipe people can still select drinking JJM water right? Because we have got a lot of cases like this where community standpipe IDs have been given to us to check why they have selected drinking JJM water but this shouldn't be the case right because they still drink JJM water just that it is a shared source

**Comment by jlowe-git** [comment]
Hi @Archi11Gupta, The JJM taps are the ones that need to be connected to the main pipeline. If we were to install the chlorine device at that main pipeline then chlorinated water would reach that tap connection. 

It's the case where many community standpipes are GP provided/from the solar tanks. However, it can be the case where it's not their primary source but they are still selecting "yes" to the question "do you drink JJM tap water?" In these cases where they are community taps though they should not be selected as "JJM Taps" for the primary source question. 

If it's the case where like 3 households are right next to each other and use the JJM tap, it's still a JJM tap, not a community standpipe. We're mostly concerned if they're using drinking water connected to the main pipeline or not and if it's close to their house. So we should make sure the primary and secondary source questions are correct in that regard.

**Comment by mich1995** [comment]
**FYI @jlowe-git @Archi11Gupta** 
Quick Stats on the above issue of people who report GP provided or other community standpipes as primary water source and also report "drinking JJM water": 11 out of 909 total census cases where this occurs 
Village-wise distribution of these 11 cases (Mukundpur- 3, Birnarayanpur- 7, Kuljing- 1)

Cases where people are report govt-provided community standpipes (which would most likely be connected to the main pipeline) as their primary drinking water source, but not drinking JJM water: 3 such cases (Jaltar, Birnaryanpur and Bichikote each have 1 case)

**Comment by mich1995** [comment]
@Archi11Gupta
For everyone's reference: Difference between Govt-provided community standpipes and GP-provided/other community standpipes: 
> Govt-provided community standpipes: JM tap is the one from the main storage tanks maintained by RWSS/JJM. If it's connected to the main water line on which we will be installing, then it'd be a JJM tap. Cases where it's a community level tap but connected to the JJM line are more rare. In most cases they're still household level taps.

>GP-provided/other community standpipes: Any other community taps connected to a smaller tank/solar tank/small tank maintained by GP we would count as the GP-provided community standpipe
