### ISSUE TITLE
Back Check survey - Specific observations for selected IDs

### ISSUE THREAD

**Issue by Archi11Gupta** [DevInnovationLab/i-h2o-india#78]
Data quality check form: 
10101-113-025 - This is a sort of unique case. This household has a borewell (motor) connection to their house but they have an JJM tap water connection at their house when the survey was being done surveyor wasn't informed about this issue and he selected the borewell as the primary water source and JJM wasn't reflected anywhere at the source. Though still their primary water source is boring JJM is their secondary source. Even though this is surveyed in data quality checks I thought of keeping it here too.

Vill Tandipur
BC ID - 30301-119-12 and 30301-119-23
These two IDs were allotted for BCs but they weren't completed because the only respondents present here were very aged ladies who couldn't answer the pregnancy and roster-related questions properly so to at least get some sense of their water usage we conducted a data quality survey here

**Comment by jlowe-git** [comment]
So for 10101-113-025, we should adjust their response in the survey right? So we should select borewell as the primary and JJM as the primary and secondary source.

For the other two in Tandipur, I think it's okay to not survey them for the backchecks. I think we want to survey the same people as last time if possible, right? Is that what we have been doing in our protocol?

**Comment by Archi11Gupta** [comment]
To your first point, yes we should make a change to the survey 
To your second point, yes this is the protocol we have been following that is to survey the same respondents only but even if after lot of attempts we are unable to find the previous respondents or any eligible respondent in that household we are left with no choice but to survey with such ladies now we are avoiding doing BC surveys with them but we do DQ surveys at least and take their answers with a pinch of salt as they really don't know the situation in the household

**Comment by Archi11Gupta** [comment]
As per the discussion in the weekly call, we decided not to reconcile data quality check answers with the main survey. So, this was not implemented as there was limited bandwidth
