### ISSUE TITLE
Bhujbhal Village (Kolnara Block) - JJM as a primary source of water reported only 51% 

### ISSUE THREAD

**Issue by Archi11Gupta** [DevInnovationLab/i-h2o-india#79]
1.	76% report JJM as a secondary water source and  70% report using JJM water for drinking (which seems a bit off because what people in the village is quite different). In Bhujbal, a very high percentage of people have Kidney issues because of the water quality issues and they are very skeptical about drinking JJM water even though there is a good supply of JJM water and most of the households have JJM taps. 
2.	The main pipeline has severe damages and leakages due to which water going through the pipeline gets dirty to drink and most of the people rely on handpumps 
3.	There are so many issues in terms of responsiveness of the government towards things like cleaning the tank, fixing the pipeline, etc. For eg- several people reported that the tank gets cleaned only once a year and whenever it gets cleaned, the amount of bleaching powder put in the tank is so high that people don't prefer drinking it for eg last year 10 kg of bleaching powder was put in the main tank due to which people didn't drink water from it for a significant time 
4.	People defecate near the main water channel which faeces get flowed into the main pipeline because of the damages present on it  
@amyjanel @elisamaffioli for your reference

**Comment by jlowe-git** [comment]
Hi @Archi11Gupta , let's discuss this village more on our weekly call. I think this village still technically meets our eligibility criteria despite the reported issues (compatible infrastructure, daily supply, majority of people using the JJM taps).

**Comment by Archi11Gupta** [comment]
This was discussed in the weekly call and we kept the village in the sample
