### ISSUE TITLE
Changed the relevance of the "drink JJM water" question to only when people say JJM tap or govt community standpipe

### ISSUE THREAD

**Issue by Archi11Gupta** [DevInnovationLab/i-h2o-india#81]
Hi all, 
I had a question regarding a specific observation we made on field during Back checks and I want your inputs on that so that I can give the instruction to the field team on time for tomorrow's data collection -

**ISSUE-** 
In the census survey, we ask the question "A18) Do you use the government-provided household tap for drinking?", now the issue at hand is that we don't give any reference period to them as opposed to other questions like "A12) In the past month, which water source did your household primarily use for drinking?" and for secondary source where we mention time period of a month.  

**IMPLICATION-** When we ask the question about drinking JJM water they say yes even if they have not chosen a JJM-related source (be it a tap connection or government-provided community standpipe in their primary or secondary source) now this issue is different from data entry errors or probing errors because here a lot of times respondents answer "Yes" because they used JJM tap 1 month ago or maybe earlier so even if now they are not using JJM tap based on the wording of the question A18 they are right to say "Yes" here because we haven't mentioned any reference period here, now there are not a lot of IDs like this but then also since we starting data collection tomorrow in the replacement villages I want to make sure what is our objective really because if we want "Yes" in this answer only when they have chosen JJM related source n their primary or secondary source and we are not concerned about them using it before 1 month then should we make a change  in the wording of the question to avoid such situations ? 
Although I have given instructions to the team to specifically probe more in such situations and select yes in drinking JJM  only when JJM has been selected as the primary or secondary source but I still think we should either change the wording of A18 drinking water question or make a relevance change in the survey cto code that this be asked only if JJM has been selected as primary or secondary source as we won't be doing data quality check surveys/back checks for the IDs of the replacement villages because of budget constraints

**ACTION TAKEN-** 
Michelle has changed the relevance of the "drink JJM water" question to only when people say JJM tap or govt community standpipe (since we're taking that to be part of the JJM infrastructure)

**Comment by jlowe-git** [comment]
Yes, I think making this question conditional makes sense

**Comment by niharika-bhagavatula** [comment]
Resolved in HH Level cleaning code
