### ISSUE TITLE
Chlorine Data Quality Check: 15 observations of false positives, Nov 8th 2023

### ISSUE THREAD

**Issue by jlowe-git** [DevInnovationLab/i-h2o-india#82]
Hi @Archi11Gupta, I did another review of the chlorine test data, and we have several (15) false positives (at least I am assuming they are false positives). I'm attaching an excel file noting these cases, if you have a chance to review them. I'm primarily concerned with the cases above 0.20. There were two cases in Naira where the reported reading was very high, around 1 mg/L.

[20231108_chlorine_data_check.csv](https://github.com/DevInnovationLab/i-h2o-india/files/13302018/20231108_chlorine_data_check.csv)

**Comment by jlowe-git** [comment]
Hi @Archi11Gupta I wanted to follow up on this. I think this is important for us to figure out if these were false positives or not, even though it happened a few months ago. We want to confirm if these were actually positive or not, but may need to rely on the enumerator's memory of testing in different villages during baseline.

cc-ing @avohra29

**Comment by Archi11Gupta** [comment]
Hi Jeremy, Is it possible to get dates for these readings? Also, I am unsure how would we verify this because these are the readings from baseline. So, do you want me to ask enumerators to show the readings for these tests they did? If they don't have these readings written in their notebooks it would be great if you could tell me what else can we do to verify these?

**Comment by jlowe-git** [comment]
Hey there, I don't think I can get the dates, but I attached a .csv file with the unique IDs from the baseline survey, so these cases can be identified that way.

I don't expect for them to be able to display their readings for this in their notebooks, but if they have tracked it that well then yes that can work. There are some cases though where the reading is very high, like close to 1.0 mg/L. That would be a very noticeable reading from the baseline, so maybe you can ask if they ever remember seeing such a high reading during the survey in those villages?

**Comment by niharika-bhagavatula** [comment]
flagged these false positives in the Baseline HH survey dataset under variable "survey_issues==2".  (Refer to code file: GitHub/i-h2o-india/Code/1_profile_ILC3_X_FU_Data_Creation.do)
