### ISSUE TITLE
Chlorine Monitoring Form -- Data entry error? For Nathma -- Feb 9th 2024

### ISSUE THREAD

**Issue by jlowe-git** [DevInnovationLab/i-h2o-india#95]
Hey there, @Archi11Gupta @avohra29,

I was checking some data manually and it looks like there may be a small entry error on results from Nathma on 9/2/24. At the nearest tap connection, they reported two free chlorine measurements of 0.08 and 0.74 mg/L. it's very unlikely that two samples taken after one another would be this different. @Archi11Gupta could you check into this when you have a chance and provide a correction?

@avohra29 can we also meet so we can try to set up a more formal data check process for this chlorine data? I just caught this one by chance with a manual check

**Comment by Archi11Gupta** [comment]
Yes, I will get back to you. I think the date should be 10th Feb 2024 because on 9th feb we were working in Gopi Kankubadi

**Comment by Archi11Gupta** [comment]
Hi Jeremy, I confirmed and found out that this is a data entry error. Thanks for flagging it. I am attaching the picture below with the correct readings
![image](https://github.com/user-attachments/assets/cea758f2-7ad0-4ef3-b682-9c4dc50a78f1)
.

**Comment by jlowe-git** [comment]
Hey there, can you edit the submitted survey form directly to change this value?

**Comment by Archi11Gupta** [comment]
Yes will do. Will also include some basic quality checks after talking to
you.

Regards,
Archi

**Comment by niharika-bhagavatula** [comment]
This error was observed for data collected in Nathma on 10thFeb 2024. Manual correction made in R script "GitHub/i-h2o-india/Code/2_Pilot/1_data cleaningIndia_ILC_Pilot_Chloirne_Monitoring.Rmd" to reflect correct FC readings
